time_step: '1 hour'
initial_state: 'zero'
area_sqkm: 620.38
lat: 44.60797
lon: -67.93524
h_t_init_file: ./data/h_t_start.csv
c_t_init_file: ./data/c_t_start.csv
train_cfg_file: ./trained_neuralhydrology_models/hourly_test_run_1008_154114/config.yml
verbose: 1
elev_mean: 92.68
slope_mean: 17.79072
